import "./globals.css";
import type { Metadata } from "next";
import { pixeboy, gohu } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pixeboy.variable} ${gohu.variable}`}>
      <body>{children}</body>
    </html>
  );
}
